// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChMffbF87UTYhOaF8i9OBXbpFQBz92TBI',
    appId: '1:445861079846:web:47909b48bd4e9d7401afe7',
    messagingSenderId: '445861079846',
    projectId: 'chatapp-cbae7',
    authDomain: 'chatapp-cbae7.firebaseapp.com',
    storageBucket: 'chatapp-cbae7.firebasestorage.app',
    measurementId: 'G-EP7QM2GF06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyaWKjQ5GviUbUBkq1Hkuth95GgSwdgI',
    appId: '1:445861079846:android:d8f6c56633404f4101afe7',
    messagingSenderId: '445861079846',
    projectId: 'chatapp-cbae7',
    storageBucket: 'chatapp-cbae7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkCuM90B0xutocnrY4ur_teTeA-IOcfto',
    appId: '1:445861079846:ios:ce41413f282e50ba01afe7',
    messagingSenderId: '445861079846',
    projectId: 'chatapp-cbae7',
    storageBucket: 'chatapp-cbae7.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkCuM90B0xutocnrY4ur_teTeA-IOcfto',
    appId: '1:445861079846:ios:ce41413f282e50ba01afe7',
    messagingSenderId: '445861079846',
    projectId: 'chatapp-cbae7',
    storageBucket: 'chatapp-cbae7.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChMffbF87UTYhOaF8i9OBXbpFQBz92TBI',
    appId: '1:445861079846:web:46a44d3562cb9e8801afe7',
    messagingSenderId: '445861079846',
    projectId: 'chatapp-cbae7',
    authDomain: 'chatapp-cbae7.firebaseapp.com',
    storageBucket: 'chatapp-cbae7.firebasestorage.app',
    measurementId: 'G-Y0H45S50Q4',
  );
}
